version: '3.7'

services:
  open-position:
    image: mmv1
    ports:
      - "8000:8000"
    networks:
      - MSN
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka

  api-gateway:
    image: api-gateway
    ports:
      - "8765:8765"
    networks:
      - MSN
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka

  job-recruitment-system:
    image: job-recruitment-system
    ports:
      - "8100:8100"
    networks:
      - MSN
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka

  naming-server:
    image: naming-server
    ports:
      - "8761:8761"
    networks:
      - MSN
networks:
  MSN: